# Python tags: https://hub.docker.com/_/python
FROM python:3.14.4-slim@sha256:c11aee3b3cae066f55d1e9318fc812673aa6557073b0db0d792b59491b262e0c

COPY install-devtools.sh /tmp/
RUN /tmp/install-devtools.sh

# Add uv to PATH
ENV PATH="/root/.local/bin:${PATH}"

COPY apply-templates merge-xml /usr/local/bin/
