# Python tags: https://hub.docker.com/_/python
FROM python:3.14.6-slim@sha256:fe45aec842a1256ca15d90f319f943c34c6d1ad0585f3c3cd4009ae23c4e932d

COPY install-devtools.sh /tmp/
RUN /tmp/install-devtools.sh

# Add uv to PATH
ENV PATH="/root/.local/bin:${PATH}"

COPY apply-templates merge-xml /usr/local/bin/
