# Python tags: https://hub.docker.com/_/python
FROM python:3.14.5-slim@sha256:c845af9399020c7e562969a13689e929074a10fd057acd1b1fad06a2fb068e97

COPY install-devtools.sh /tmp/
RUN /tmp/install-devtools.sh

# Add uv to PATH
ENV PATH="/root/.local/bin:${PATH}"

COPY apply-templates merge-xml /usr/local/bin/
